# -*- coding: utf-8 -*-
"""apuracao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNcYZzil7Gkvo_v1W-g7iBhOSEeBu_rL
"""

import requests
import json
import pandas as pd
import time
from IPython.display import clear_output

while True:
  try:
    data = requests.get(
        'https://resultados.tse.jus.br/oficial/ele2022/544/dados-simplificados/br/br-c0001-e000544-r.json'
    )

    json_data = json.loads(data.content)

    candidato = []
    partido = []
    votos = []
    porcentagem = []

    for informacoes in json_data['cand']:
      candidato.append(informacoes['nm'])
      votos.append(informacoes['vap'])
      porcentagem.append(informacoes['pvap'])

    df_eleicao = pd.DataFrame(
        list(zip(candidato, votos, porcentagem)),
        columns = ['Candidatos', 'Nº Votos', 'Porcentagem']
    )

    clear_output(wait = True)
    print(f"{json_data['pst'].replace(',', '.')} % das urnas apuradas")
    display(df_eleicao.head(10))
    time.sleep(5)
  
  except Exception:
    pass